Update environment.yml
java and javajdk and beagle again since it makes a trouble..

Command error:
  Error: Unable to access jarfile beagle.18May.d20.jar